# 4 routes
# GET pierre / papier / ciseaux
# GET Score
# POST remettre à zéro


GET localhost:3000/game/score
# {
#     "win": 100,
#     "lose": 5,
#     "tie": 0
# }

###

GET localhost:3000/game/play/rock
# GET /game/play/(pierre | feuille | ciseaux) 
# Vous avez joué :action, le serveur a joué :action_serv vous avez fait :result

###

PUT localhost:3000/game/score/:win/:lose/:tie
Content-Type: application/json
# PUT /game/score/:wins/:loses/:ties

{
  "win": "win",
  "lose": "lose",
  "tie": "tie"
}

###

POST localhost:3000/game/restart
# {
#   "win": 0,
#   "lose": 0,
#   "tie": 0
# }